# Generated by Django 3.0.5 on 2020-11-22 20:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201121_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cod_juego', models.CharField(max_length=15, verbose_name='Codigo Juego')),
                ('tienda1', models.CharField(max_length=25, verbose_name='Zmart')),
                ('tienda2', models.CharField(max_length=25, verbose_name='MicroPlay')),
                ('tienda3', models.CharField(max_length=25, verbose_name='Weplay')),
                ('precio1', models.IntegerField(verbose_name='Precio Zmart')),
                ('precio2', models.IntegerField(verbose_name='Precio Microplay')),
                ('precio3', models.IntegerField(verbose_name='Precio Weplay')),
                ('enlace1', models.CharField(max_length=250, verbose_name='Link Zmart')),
                ('enlace2', models.CharField(max_length=250, verbose_name='Link MicroPlay')),
                ('enlace3', models.CharField(max_length=250, verbose_name='Link Weplay')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado el ')),
            ],
        ),
        migrations.AlterField(
            model_name='juego',
            name='cod_juego',
            field=models.CharField(max_length=15, verbose_name='Codigo Juego'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el '),
        ),
        migrations.AlterField(
            model_name='juego',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado el '),
        ),
        migrations.CreateModel(
            name='Game_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_juego', models.CharField(max_length=15)),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('link_imagen', models.TextField(default='null')),
                ('titulo_juego', models.CharField(default='null', max_length=50)),
                ('game', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='pages.Game', verbose_name='Juego')),
            ],
        ),
    ]
