# Generated by Django 3.0.5 on 2020-11-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201122_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_detail',
            name='game',
        ),
        migrations.AddField(
            model_name='game_detail',
            name='fk_juego',
            field=models.ManyToManyField(blank=True, to='pages.Game', verbose_name='Juegos'),
        ),
    ]
