# Generated by Django 3.1.3 on 2020-12-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201122_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='preciomasbajo',
            field=models.IntegerField(default=0, verbose_name='Precio mas bajo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(verbose_name='Creado el '),
        ),
        migrations.AlterField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Editado el '),
        ),
    ]
